// Code generated by "gocd-response-links-generator -type=BuildDetailsLinks"; DO NOT EDIT.

package gocd

import (
	"encoding/json"
	"net/url"
)

func (l BuildDetailsLinks) MarshalJSON() ([]byte, error) {
	type h struct {
		H string `json:"href"`
	}
	ls := struct {
		Job      *h `json:"job,omitempty"`
		Stage    *h `json:"stage,omitempty"`
		Pipeline *h `json:"pipeline,omitempty"`
	}{}
	if l.Job != nil {
		ls.Job = &h{H: l.Job.String()}
	}
	if l.Stage != nil {
		ls.Stage = &h{H: l.Stage.String()}
	}
	if l.Pipeline != nil {
		ls.Pipeline = &h{H: l.Pipeline.String()}
	}
	j, e := json.Marshal(ls)
	if e != nil {
		return nil, e
	}
	return j, nil
}

func (l *BuildDetailsLinks) UnmarshalJSON(j []byte) error {
	var d map[string]map[string]string
	e := json.Unmarshal(j, &d)
	if e != nil {
		return e
	}

	if h := d["job"]["href"]; h != "" {
		l.Job, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	if h := d["stage"]["href"]; h != "" {
		l.Stage, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	if h := d["pipeline"]["href"]; h != "" {
		l.Pipeline, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	return nil
}
