// Code generated by "gocd-response-links-generator -type=PipelineTemplatesLinks,PipelineTemplateLinks"; DO NOT EDIT.

package gocd

import (
	"encoding/json"
	"net/url"
)

func (l PipelineTemplatesLinks) MarshalJSON() ([]byte, error) {
	type h struct {
		H string `json:"href"`
	}
	ls := struct {
		Self *h `json:"self,omitempty"`
		Doc  *h `json:"doc,omitempty"`
		Find *h `json:"find,omitempty"`
	}{}
	if l.Self != nil {
		ls.Self = &h{H: l.Self.String()}
	}
	if l.Doc != nil {
		ls.Doc = &h{H: l.Doc.String()}
	}
	if l.Find != nil {
		ls.Find = &h{H: l.Find.String()}
	}
	j, e := json.Marshal(ls)
	if e != nil {
		return nil, e
	}
	return j, nil
}

func (l *PipelineTemplatesLinks) UnmarshalJSON(j []byte) error {
	var d map[string]map[string]string
	e := json.Unmarshal(j, &d)
	if e != nil {
		return e
	}

	if h := d["self"]["href"]; h != "" {
		l.Self, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	if h := d["doc"]["href"]; h != "" {
		l.Doc, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	if h := d["find"]["href"]; h != "" {
		l.Find, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	return nil
}
func (l PipelineTemplateLinks) MarshalJSON() ([]byte, error) {
	type h struct {
		H string `json:"href"`
	}
	ls := struct {
		Self *h `json:"self,omitempty"`
		Doc  *h `json:"doc,omitempty"`
		Find *h `json:"find,omitempty"`
	}{}
	if l.Self != nil {
		ls.Self = &h{H: l.Self.String()}
	}
	if l.Doc != nil {
		ls.Doc = &h{H: l.Doc.String()}
	}
	if l.Find != nil {
		ls.Find = &h{H: l.Find.String()}
	}
	j, e := json.Marshal(ls)
	if e != nil {
		return nil, e
	}
	return j, nil
}

func (l *PipelineTemplateLinks) UnmarshalJSON(j []byte) error {
	var d map[string]map[string]string
	e := json.Unmarshal(j, &d)
	if e != nil {
		return e
	}

	if h := d["self"]["href"]; h != "" {
		l.Self, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	if h := d["doc"]["href"]; h != "" {
		l.Doc, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	if h := d["find"]["href"]; h != "" {
		l.Find, e = url.Parse(h)
		if e != nil {
			return e
		}
	}
	return nil
}
